[tool.poetry]
name = "thumbnailer"
version = "0.1.0"
description = ""
authors = ["Edward Q. Bridges <github@eqbridges.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pillow = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
lgw = "^1.0.9"
boto3 = "^1.13.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
